class Constants:
    LIGHT_OFF_PWM_VAL = 0.0
    LIGHT_DIM_PWM_VAL = 0.02
    LIGHT_BRIGHT_PWM_VAL = 1.0
    LIGHT_BLINK_DURATION_NS = pow(10, 9) / 2
    SERVO_CENTER_PWM_VALUE = -0.3
    MOTOR_FWD_THROTTLE_LIMIT = 0.5
    MOTOR_REV_THROTTLE_LIMIT = -0.5

    GPIO_PIN_HEADLIGHTS = 2
    GPIO_PIN_FOGLIGHTS = 14
    GPIO_PIN_LEFT_TURNSIGNAL = 4
    GPIO_PIN_RIGHT_TURNSIGNAL = 3

    GPIO_PIN_LEFT_TAILLIGHT = 27
    GPIO_PIN_RIGHT_TAILLIGHT = 17
    GPIO_PIN_REVERSE_LIGHTS = 22

    GPIO_PIN_ELECTRONIC_SPEED_CONTROLLER = 12
    GPIO_PIN_STEERING_SERVO = 13

